### ISSUE TITLE
GTK 4/5 support possible?

### ISSUE THREAD

**Issue by ipkpjersi** [B00merang-Project/Windows-XP#47]
Hi,

I love this project! I was just wondering, would GTK 4/5 support be possible, would this theme work out of the box on those in theory or would it need to be upgraded? This is more of an information gathering issue than anything else because I am curious how this would work.

Cheers.

**Comment by Elbullazul** [comment]
There is some GTK4 support in the master branch, but some details still need to be ironed out before it's fully supported.

**Comment by ipkpjersi** [comment]
Do newer GTK versions tend to have a lot of breaking changes requiring basically like a complete rewrite for themes, or is it usually not too bad? I'm hoping to continue using this theme years and years into the future because of how good it is, but I'm just not sure if it's an insane amount of work to keep upgrading GTK version support and maybe one day this theme will no longer be upgraded.

The fact it's not fully supported yet makes me worry it's a ton of work :worried:

**Comment by Elbullazul** [comment]
Normally migrating to newer GTK versions isn't so hard, but the issue I have is that for Gnome 40+ you need to support gtk4 and libadwaita if you want to theme all the apps, so it's almost like remaking every theme one and a half times to support the latest Gnome release.

Shell themes have also gotten little attention and some of them started breaking since Gnome 40 too.

In the end, it's very possible to support GTK 4, but there's still a substantial amount of work to be done, and I'm the only dev and don't have much time available lately

**Comment by ipkpjersi** [comment]
I got my question answered so I will go ahead and close this, thanks for taking the time to answer me :+1:
